//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ipos_pawneditem_terms
    {
        public long autonum { get; set; }
        public string term_desc { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<decimal> multiplier { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string updaed_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
    }
}
