//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int autonum { get; set; }
        public int id_code { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string department { get; set; }
        public string designation { get; set; }
        public string home_phone_no { get; set; }
        public string mobile_no { get; set; }
        public string fax_no { get; set; }
        public string st_address { get; set; }
        public string city_address { get; set; }
        public Nullable<int> zip_code { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string place_of_birth { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<System.DateTime> date_as_of { get; set; }
        public string active { get; set; }
        public string remarks { get; set; }
        public byte[] employee_image { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<int> ul_code { get; set; }
        public string Manual_YN { get; set; }
    }
}
