//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ipos_pawneditem_amortization_schedule
    {
        public long autonum { get; set; }
        public string transaction_no { get; set; }
        public Nullable<int> pawned_item_id { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<decimal> principal { get; set; }
        public Nullable<decimal> interest { get; set; }
        public Nullable<decimal> penalty { get; set; }
        public Nullable<decimal> amount_due { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string or_no { get; set; }
        public Nullable<decimal> principal_payment { get; set; }
        public Nullable<decimal> interest_payment { get; set; }
        public Nullable<decimal> penalty_payment { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isDisabled { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
